#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
if __name__ == '__main__':
    # Ввести список одной строкой.
    a = list(map(int, input().split()))
    # Если список пуст, завершить программу.
    if not a:
        print("Заданный список пуст", file=sys.stderr)
        exit(1)
    # Определить индексы минимального и максимального элементов.
    a_min = a_max = a[0]
    i_min = i_max = 0
    for i, item in enumerate(a):
        if item < a_min:
            i_min, a_min = i, item

        if item >= a_max:
            i_max, a_max = i, item
    # Проверить индексы и обменять их местами.
    if i_min > i_max:
        i_min, i_max = i_max, i_min
    from functools import reduce
    b = reduce(lambda x, y: x * y, a[i_min + 1:i_max])
    print("произведение элементов между max и min равно", b)
    # Отфильтруем положительные числа в отдельный список.
    filtered_lst2 = list(filter(lambda item: (item > 0), a))
    # Подсчитать сумму положительных чисел
    s = sum([a for a in filtered_lst2])
    print("Сумма положительных элементов списка равна", s)
    print(sorted(a))
